### PR TITLE
Homework 1

### PR DESCRIPTION
**Pull request by a-s01**

### CODE REVIEW

**Comment by KostyantynPanchenko** [comment]
Well done. Please fix minor issues.

**Comment by KostyantynPanchenko** [comment]
Recommendation for commit messages - I would go with the following template `HW_{homework_number} - description of what was done`.

Simplest example would be:
`HW_1 - implement items 1-5`
`HW_1 - implement items 6-9`
`HW_1 - implement item 10`

More verbose and understandable:
`HW_1 - implement POJO classes and base configuration class`
`HW_1 - provide implementations for Animal interface and extend configuration with PetConfig`
`HW_1 - add  more options with Primary and Qualifier annotations`

**Comment by a-s01** [comment]
Thanks for pointing it out. 
Please, check the updated version in a new pull request: https://github.com/a-s01/alyona.sol-hw/pull/2

**Comment by KostyantynPanchenko** [comment]
Hi @a-s01 , there is no need in creating separate pool request as new one does not preserve the history of comments/replies. Please delete pool request #2 and just push a commit with fixes to current PR.

Regarding #2 - still some new lines should be added at the end of the class in:
* BeanConfig
* PetConfig
* OtherBeanB
* Pet
* Spider

Pay attention to that red sign at the end of the class - it signals that a new line should be added at the end.
New_line_at_the_end_of_the_class_is_required

**Comment by a-s01** [comment]
I thought that commit messages were my issues, that's why I created a new branch with new PR :) New lines are fixed now. Thanks!

**Comment by KostyantynPanchenko** [comment]
@a-s01 , your commit messages are Ok, I just gave an idea for future commit messages improvement :) Having a prefix of `HW-{homework_number}` plus description of what exactly was done will contribute to better understanding of the changes. History is important.

You can merge this RP.

**Pull request merged**
